# Generated by Django 5.0.3 on 2024-07-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackCard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("back_card_content", models.TextField()),
                ("description", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("repeat_num", models.IntegerField()),
                ("next_study_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="CardRelation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("front_id", models.IntegerField()),
                ("back_id", models.IntegerField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FrontCard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("front_card_content", models.TextField()),
                ("description", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("repeat_num", models.IntegerField()),
                ("next_study_time", models.DateTimeField()),
            ],
        ),
    ]
