# Generated by Django 5.0.3 on 2024-07-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="backcard",
            old_name="id",
            new_name="back_id",
        ),
        migrations.RenameField(
            model_name="cardrelation",
            old_name="id",
            new_name="card_id",
        ),
        migrations.RenameField(
            model_name="frontcard",
            old_name="id",
            new_name="front_id",
        ),
        migrations.AlterField(
            model_name="backcard",
            name="repeat_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="frontcard",
            name="repeat_num",
            field=models.IntegerField(default=0),
        ),
    ]
