# Generated by Django 5.0.3 on 2026-02-15 05:44

import django.db.models.deletion
from django.db import migrations, models


def add_start_recite_time_point_if_missing(apps, schema_editor):
    connection = schema_editor.connection
    quote_name = schema_editor.quote_name

    with connection.cursor() as cursor:
        table_names = set(connection.introspection.table_names(cursor))

        for table_name in ("server_backcard", "server_frontcard"):
            if table_name not in table_names:
                continue

            columns = {
                column.name
                for column in connection.introspection.get_table_description(
                    cursor, table_name
                )
            }
            if "start_recite_time_point" in columns:
                continue

            schema_editor.execute(
                f"ALTER TABLE {quote_name(table_name)} ADD COLUMN "
                f"{quote_name('start_recite_time_point')} datetime NULL"
            )


def create_recitehistory_if_missing(apps, schema_editor):
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        table_names = set(connection.introspection.table_names(cursor))

    model = apps.get_model("server", "ReciteHistory")
    if model._meta.db_table in table_names:
        return

    schema_editor.create_model(model)


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_backcard_content_type_frontcard_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="文章题目/标题")),
                (
                    "image_path",
                    models.CharField(blank=True, max_length=500, verbose_name="题目图片路径"),
                ),
                (
                    "exam_type",
                    models.CharField(
                        default="ielts", max_length=50, verbose_name="考试类型"
                    ),
                ),
                (
                    "article_type",
                    models.CharField(blank=True, max_length=100, verbose_name="文章类型"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="自定义标签"),
                ),
                ("difficulty", models.IntegerField(default=3, verbose_name="难度等级")),
                (
                    "topic",
                    models.CharField(blank=True, max_length=100, verbose_name="话题分类"),
                ),
                ("content", models.TextField(verbose_name="完整文章内容")),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="是否系统预设"),
                ),
                ("created_by", models.IntegerField(default=0, verbose_name="创建者ID")),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-create_time"],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="ReciteHistory",
                    fields=[
                        ("recite_id", models.AutoField(primary_key=True, serialize=False)),
                        ("type", models.IntegerField(default=0)),
                        ("recite_num", models.IntegerField(default=0)),
                        ("create_time", models.DateTimeField(auto_now_add=True)),
                    ],
                ),
            ],
        ),
        migrations.RunPython(
            create_recitehistory_if_missing,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="VoiceTranslateHistory",
            fields=[
                ("voice_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(default=0)),
                ("voice_text", models.TextField()),
                ("translate_text", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_start_recite_time_point_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="backcard",
                    name="start_recite_time_point",
                    field=models.DateTimeField(default=None, null=True),
                ),
                migrations.AddField(
                    model_name="frontcard",
                    name="start_recite_time_point",
                    field=models.DateTimeField(default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleSentence",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sequence", models.IntegerField(verbose_name="句子在文章中的顺序")),
                ("english", models.TextField(verbose_name="英文原句")),
                ("chinese", models.TextField(verbose_name="中文翻译")),
                (
                    "is_key_sentence",
                    models.BooleanField(default=True, verbose_name="是否重点句"),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="server.article",
                    ),
                ),
            ],
            options={
                "db_table": "article_sentences",
                "ordering": ["article", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="SentenceLearningLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(default=0, verbose_name="用户ID")),
                ("user_translation", models.TextField(verbose_name="用户翻译内容")),
                (
                    "ai_evaluation",
                    models.JSONField(blank=True, null=True, verbose_name="AI评测结果"),
                ),
                ("has_error", models.BooleanField(default=False, verbose_name="是否有错误")),
                ("study_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sentence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_logs",
                        to="server.articlesentence",
                    ),
                ),
            ],
            options={
                "db_table": "sentence_learning_logs",
                "ordering": ["-study_date"],
            },
        ),
    ]
