# Generated by Django 4.2.14 on 2026-02-08 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_backcard_content_type_frontcard_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(verbose_name='句子在文章中的顺序')),
                ('english', models.TextField(verbose_name='英文原句')),
                ('chinese', models.TextField(verbose_name='中文翻译')),
                ('is_key_sentence', models.BooleanField(default=True, verbose_name='是否重点句')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article_sentences',
                'ordering': ['article', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='IELTSArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('type', models.IntegerField(default=2, verbose_name='文章类型')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='话题分类')),
                ('difficulty', models.IntegerField(default=3, verbose_name='难度等级')),
                ('content', models.TextField(verbose_name='完整文章内容')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统预设')),
                ('created_by', models.IntegerField(default=0, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ielts_articles',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ReciteHistory',
            fields=[
                ('recite_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('recite_num', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceTranslateHistory',
            fields=[
                ('voice_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('voice_text', models.TextField()),
                ('translate_text', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='backcard',
            name='start_recite_time_point',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='frontcard',
            name='start_recite_time_point',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='SentenceLearningLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('user_translation', models.TextField(verbose_name='用户翻译内容')),
                ('ai_evaluation', models.JSONField(blank=True, null=True, verbose_name='AI评测结果')),
                ('has_error', models.BooleanField(default=False, verbose_name='是否有错误')),
                ('study_date', models.DateTimeField(auto_now_add=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_logs', to='server.articlesentence')),
            ],
            options={
                'db_table': 'sentence_learning_logs',
                'ordering': ['-study_date'],
            },
        ),
        migrations.AddField(
            model_name='articlesentence',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='server.ieltsarticle'),
        ),
    ]
