# Generated by Django 4.2.14 on 2026-02-08 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_articlesentence_ieltsarticle_recitehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='文章题目/标题')),
                ('image_path', models.CharField(blank=True, max_length=500, verbose_name='题目图片路径')),
                ('exam_type', models.CharField(default='ielts', max_length=50, verbose_name='考试类型')),
                ('article_type', models.CharField(blank=True, max_length=100, verbose_name='文章类型')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='自定义标签')),
                ('difficulty', models.IntegerField(default=3, verbose_name='难度等级')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='话题分类')),
                ('content', models.TextField(verbose_name='完整文章内容')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统预设')),
                ('created_by', models.IntegerField(default=0, verbose_name='创建者ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='articlesentence',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='server.article'),
        ),
        migrations.DeleteModel(
            name='IELTSArticle',
        ),
    ]
